<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
$data           = $this->helper("Lof\Mautic\Helper\Data");
if ($data->isEnabled()):
$baseMauticUrl = $data->getMauticBaseUrl();
?>
<script>
require([
'jquery',
'mage/url',
'domReady!'
], function($, url){
    url.setBaseUrl('<?= $block->getBaseUrl(); ?>');
    const requestUrl = url.build('rest/V1/lof-mautic/visitor/get');
    const mauticBaseUrl = '<?= $block->escapeUrl($baseMauticUrl); ?>';
    $.ajax({
        url: requestUrl,
        type: 'GET',
        success: function(data){
            if (!data || !data.email) {
                return;
            }
            (function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
                w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
                m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
            })(window,document,'script',mauticBaseUrl+'/mtc.js','mt');

            mt('send', 'pageview', data);
        }
    })
})</script>
<?php endif; ?>
