<?php echo $block->getDisabledButtonHtml() ?>
<?php if (!$this->getStoredAccessTokenData()) : ?>
<p class="note">
    <span><?php echo __("You must first configure your Mautic API keys before you can configure webhooks"); ?></span><br/>
    <span><?php echo __('A webhook will automatically be configured in your Mautic account which will point to: <br/>OAuth 1 <a href="%1" target="_blank" rel="noopener noreferrer">%1</a> and <br/>OAuth 2: <span>%2</span>. Please ensure that this link is externally accessible. Existing webhook configurations will be upgraded. A reconfigure is necessary when you change your Mautic API keys or your website Base URL.', $block->getAuthorizeUrl(), $block->getAuthorizeUrl(2)); ?></span>
</p>
<?php else: ?>
<p class="note">
    <span><?php echo __("The API was authorized."); ?></span>
</p>
<?php
endif;
?>
