<script>
    require([
        'jquery',
        'prototype'
    ],
    function(jQuery)
    {
        var progressSpan = jQuery('#exportProgress');

        jQuery('#mautic_contact_export').click(function ()
        {
            jQuery('#mautic_export_errors').hide();
            var params = {};
            new Ajax.Request('<?php echo $block->getAjaxCheckUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                method:     'get',
                onCreate: function() {
                    progressSpan.find('.configured').hide();
                    progressSpan.find('.processing').show();
                    jQuery('#mautic_exported_message').text('');
                    document.getElementById("mautic_contact_export").disabled = true;
                },
                onSuccess: function(response)
                {
                    progressSpan.find('.processing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Completed';
                        progressSpan.find('.configured').show();
                    }
                    jQuery('#mautic_exported_message').text(resultText);

                    try
                    {
                        if (typeof response.responseJSON.errors == "number" && response.responseJSON.errors > 0)
                        {
                            jQuery('#mautic_export_errors').show();
                            if (response.responseJSON.errors == 1)
                                jQuery('#mautic_export_errors .message').text(response.responseJSON.errors + " error was logged under var/log/mautic_webhooks.log");
                            else if (response.responseJSON.errors > 1)
                                jQuery('#mautic_export_errors .message').text(response.responseJSON.errors + " errors were logged under var/log/mautic_webhooks.log");
                        }
                    }
                    catch (e)
                    {
                        console.warn(e);
                    }
                },
                onFailure: function(response)
                {
                    progressSpan.find('.processing').hide();
                    jQuery('#mautic_exported_message').text("Failed");
                },
                onComplete: function()
                {
                    document.getElementById("mautic_export_errors").disabled = false;
                }
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="mautic-webhooks-config-admin" id="exportProgress">
    <img class="processing" hidden="hidden" alt="Configuring" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="configured" hidden="hidden" alt="Configured" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="mautic_exported_message"></span>
    <div id="mautic_export_errors" class="message-system-inner">
        <div class="message message-warning"></div>
    </div>
</span>
